// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: xai/api/v1/types.proto

package xaiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HNSWMetric int32

const (
	HNSWMetric_HNSW_METRIC_UNKNOWN       HNSWMetric = 0
	HNSWMetric_HNSW_METRIC_COSINE        HNSWMetric = 1
	HNSWMetric_HNSW_METRIC_EUCLIDEAN     HNSWMetric = 2
	HNSWMetric_HNSW_METRIC_INNER_PRODUCT HNSWMetric = 3
)

// Enum value maps for HNSWMetric.
var (
	HNSWMetric_name = map[int32]string{
		0: "HNSW_METRIC_UNKNOWN",
		1: "HNSW_METRIC_COSINE",
		2: "HNSW_METRIC_EUCLIDEAN",
		3: "HNSW_METRIC_INNER_PRODUCT",
	}
	HNSWMetric_value = map[string]int32{
		"HNSW_METRIC_UNKNOWN":       0,
		"HNSW_METRIC_COSINE":        1,
		"HNSW_METRIC_EUCLIDEAN":     2,
		"HNSW_METRIC_INNER_PRODUCT": 3,
	}
)

func (x HNSWMetric) Enum() *HNSWMetric {
	p := new(HNSWMetric)
	*p = x
	return p
}

func (x HNSWMetric) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HNSWMetric) Descriptor() protoreflect.EnumDescriptor {
	return file_xai_api_v1_types_proto_enumTypes[0].Descriptor()
}

func (HNSWMetric) Type() protoreflect.EnumType {
	return &file_xai_api_v1_types_proto_enumTypes[0]
}

func (x HNSWMetric) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HNSWMetric.Descriptor instead.
func (HNSWMetric) EnumDescriptor() ([]byte, []int) {
	return file_xai_api_v1_types_proto_rawDescGZIP(), []int{0}
}

type IndexConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexConfiguration) Reset() {
	*x = IndexConfiguration{}
	mi := &file_xai_api_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexConfiguration) ProtoMessage() {}

func (x *IndexConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexConfiguration.ProtoReflect.Descriptor instead.
func (*IndexConfiguration) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *IndexConfiguration) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type CharsConfiguration struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaxChunkSizeChars int32                  `protobuf:"varint,1,opt,name=max_chunk_size_chars,json=maxChunkSizeChars,proto3" json:"max_chunk_size_chars,omitempty"`
	ChunkOverlapChars int32                  `protobuf:"varint,2,opt,name=chunk_overlap_chars,json=chunkOverlapChars,proto3" json:"chunk_overlap_chars,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CharsConfiguration) Reset() {
	*x = CharsConfiguration{}
	mi := &file_xai_api_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharsConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharsConfiguration) ProtoMessage() {}

func (x *CharsConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharsConfiguration.ProtoReflect.Descriptor instead.
func (*CharsConfiguration) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *CharsConfiguration) GetMaxChunkSizeChars() int32 {
	if x != nil {
		return x.MaxChunkSizeChars
	}
	return 0
}

func (x *CharsConfiguration) GetChunkOverlapChars() int32 {
	if x != nil {
		return x.ChunkOverlapChars
	}
	return 0
}

type TokensConfiguration struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MaxChunkSizeTokens int32                  `protobuf:"varint,1,opt,name=max_chunk_size_tokens,json=maxChunkSizeTokens,proto3" json:"max_chunk_size_tokens,omitempty"`
	ChunkOverlapTokens int32                  `protobuf:"varint,2,opt,name=chunk_overlap_tokens,json=chunkOverlapTokens,proto3" json:"chunk_overlap_tokens,omitempty"`
	EncodingName       string                 `protobuf:"bytes,3,opt,name=encoding_name,json=encodingName,proto3" json:"encoding_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TokensConfiguration) Reset() {
	*x = TokensConfiguration{}
	mi := &file_xai_api_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokensConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokensConfiguration) ProtoMessage() {}

func (x *TokensConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokensConfiguration.ProtoReflect.Descriptor instead.
func (*TokensConfiguration) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *TokensConfiguration) GetMaxChunkSizeTokens() int32 {
	if x != nil {
		return x.MaxChunkSizeTokens
	}
	return 0
}

func (x *TokensConfiguration) GetChunkOverlapTokens() int32 {
	if x != nil {
		return x.ChunkOverlapTokens
	}
	return 0
}

func (x *TokensConfiguration) GetEncodingName() string {
	if x != nil {
		return x.EncodingName
	}
	return ""
}

type BytesConfiguration struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaxChunkSizeBytes int32                  `protobuf:"varint,1,opt,name=max_chunk_size_bytes,json=maxChunkSizeBytes,proto3" json:"max_chunk_size_bytes,omitempty"`
	ChunkOverlapBytes int32                  `protobuf:"varint,2,opt,name=chunk_overlap_bytes,json=chunkOverlapBytes,proto3" json:"chunk_overlap_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BytesConfiguration) Reset() {
	*x = BytesConfiguration{}
	mi := &file_xai_api_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytesConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesConfiguration) ProtoMessage() {}

func (x *BytesConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesConfiguration.ProtoReflect.Descriptor instead.
func (*BytesConfiguration) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *BytesConfiguration) GetMaxChunkSizeBytes() int32 {
	if x != nil {
		return x.MaxChunkSizeBytes
	}
	return 0
}

func (x *BytesConfiguration) GetChunkOverlapBytes() int32 {
	if x != nil {
		return x.ChunkOverlapBytes
	}
	return 0
}

type ChunkConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one chunking strategy (enforced by oneof, matching upstream).
	//
	// Types that are valid to be assigned to Config:
	//
	//	*ChunkConfiguration_CharsConfiguration
	//	*ChunkConfiguration_TokensConfiguration
	//	*ChunkConfiguration_BytesConfiguration
	Config               isChunkConfiguration_Config `protobuf_oneof:"config"`
	StripWhitespace      bool                        `protobuf:"varint,3,opt,name=strip_whitespace,json=stripWhitespace,proto3" json:"strip_whitespace,omitempty"`
	InjectNameIntoChunks bool                        `protobuf:"varint,4,opt,name=inject_name_into_chunks,json=injectNameIntoChunks,proto3" json:"inject_name_into_chunks,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ChunkConfiguration) Reset() {
	*x = ChunkConfiguration{}
	mi := &file_xai_api_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkConfiguration) ProtoMessage() {}

func (x *ChunkConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkConfiguration.ProtoReflect.Descriptor instead.
func (*ChunkConfiguration) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *ChunkConfiguration) GetConfig() isChunkConfiguration_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ChunkConfiguration) GetCharsConfiguration() *CharsConfiguration {
	if x != nil {
		if x, ok := x.Config.(*ChunkConfiguration_CharsConfiguration); ok {
			return x.CharsConfiguration
		}
	}
	return nil
}

func (x *ChunkConfiguration) GetTokensConfiguration() *TokensConfiguration {
	if x != nil {
		if x, ok := x.Config.(*ChunkConfiguration_TokensConfiguration); ok {
			return x.TokensConfiguration
		}
	}
	return nil
}

func (x *ChunkConfiguration) GetBytesConfiguration() *BytesConfiguration {
	if x != nil {
		if x, ok := x.Config.(*ChunkConfiguration_BytesConfiguration); ok {
			return x.BytesConfiguration
		}
	}
	return nil
}

func (x *ChunkConfiguration) GetStripWhitespace() bool {
	if x != nil {
		return x.StripWhitespace
	}
	return false
}

func (x *ChunkConfiguration) GetInjectNameIntoChunks() bool {
	if x != nil {
		return x.InjectNameIntoChunks
	}
	return false
}

type isChunkConfiguration_Config interface {
	isChunkConfiguration_Config()
}

type ChunkConfiguration_CharsConfiguration struct {
	CharsConfiguration *CharsConfiguration `protobuf:"bytes,1,opt,name=chars_configuration,json=charsConfiguration,proto3,oneof"`
}

type ChunkConfiguration_TokensConfiguration struct {
	TokensConfiguration *TokensConfiguration `protobuf:"bytes,2,opt,name=tokens_configuration,json=tokensConfiguration,proto3,oneof"`
}

type ChunkConfiguration_BytesConfiguration struct {
	BytesConfiguration *BytesConfiguration `protobuf:"bytes,11,opt,name=bytes_configuration,json=bytesConfiguration,proto3,oneof"`
}

func (*ChunkConfiguration_CharsConfiguration) isChunkConfiguration_Config() {}

func (*ChunkConfiguration_TokensConfiguration) isChunkConfiguration_Config() {}

func (*ChunkConfiguration_BytesConfiguration) isChunkConfiguration_Config() {}

var File_xai_api_v1_types_proto protoreflect.FileDescriptor

const file_xai_api_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x16xai/api/v1/types.proto\x12\axai_api\"3\n" +
	"\x12IndexConfiguration\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\"u\n" +
	"\x12CharsConfiguration\x12/\n" +
	"\x14max_chunk_size_chars\x18\x01 \x01(\x05R\x11maxChunkSizeChars\x12.\n" +
	"\x13chunk_overlap_chars\x18\x02 \x01(\x05R\x11chunkOverlapChars\"\x9f\x01\n" +
	"\x13TokensConfiguration\x121\n" +
	"\x15max_chunk_size_tokens\x18\x01 \x01(\x05R\x12maxChunkSizeTokens\x120\n" +
	"\x14chunk_overlap_tokens\x18\x02 \x01(\x05R\x12chunkOverlapTokens\x12#\n" +
	"\rencoding_name\x18\x03 \x01(\tR\fencodingName\"u\n" +
	"\x12BytesConfiguration\x12/\n" +
	"\x14max_chunk_size_bytes\x18\x01 \x01(\x05R\x11maxChunkSizeBytes\x12.\n" +
	"\x13chunk_overlap_bytes\x18\x02 \x01(\x05R\x11chunkOverlapBytes\"\xf3\x02\n" +
	"\x12ChunkConfiguration\x12N\n" +
	"\x13chars_configuration\x18\x01 \x01(\v2\x1b.xai_api.CharsConfigurationH\x00R\x12charsConfiguration\x12Q\n" +
	"\x14tokens_configuration\x18\x02 \x01(\v2\x1c.xai_api.TokensConfigurationH\x00R\x13tokensConfiguration\x12N\n" +
	"\x13bytes_configuration\x18\v \x01(\v2\x1b.xai_api.BytesConfigurationH\x00R\x12bytesConfiguration\x12)\n" +
	"\x10strip_whitespace\x18\x03 \x01(\bR\x0fstripWhitespace\x125\n" +
	"\x17inject_name_into_chunks\x18\x04 \x01(\bR\x14injectNameIntoChunksB\b\n" +
	"\x06config*w\n" +
	"\n" +
	"HNSWMetric\x12\x17\n" +
	"\x13HNSW_METRIC_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12HNSW_METRIC_COSINE\x10\x01\x12\x19\n" +
	"\x15HNSW_METRIC_EUCLIDEAN\x10\x02\x12\x1d\n" +
	"\x19HNSW_METRIC_INNER_PRODUCT\x10\x03B0Z.github.com/fun7257/xai-sdk-go/xai/api/v1;xaiv1b\x06proto3"

var (
	file_xai_api_v1_types_proto_rawDescOnce sync.Once
	file_xai_api_v1_types_proto_rawDescData []byte
)

func file_xai_api_v1_types_proto_rawDescGZIP() []byte {
	file_xai_api_v1_types_proto_rawDescOnce.Do(func() {
		file_xai_api_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xai_api_v1_types_proto_rawDesc), len(file_xai_api_v1_types_proto_rawDesc)))
	})
	return file_xai_api_v1_types_proto_rawDescData
}

var file_xai_api_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xai_api_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_xai_api_v1_types_proto_goTypes = []any{
	(HNSWMetric)(0),             // 0: xai_api.HNSWMetric
	(*IndexConfiguration)(nil),  // 1: xai_api.IndexConfiguration
	(*CharsConfiguration)(nil),  // 2: xai_api.CharsConfiguration
	(*TokensConfiguration)(nil), // 3: xai_api.TokensConfiguration
	(*BytesConfiguration)(nil),  // 4: xai_api.BytesConfiguration
	(*ChunkConfiguration)(nil),  // 5: xai_api.ChunkConfiguration
}
var file_xai_api_v1_types_proto_depIdxs = []int32{
	2, // 0: xai_api.ChunkConfiguration.chars_configuration:type_name -> xai_api.CharsConfiguration
	3, // 1: xai_api.ChunkConfiguration.tokens_configuration:type_name -> xai_api.TokensConfiguration
	4, // 2: xai_api.ChunkConfiguration.bytes_configuration:type_name -> xai_api.BytesConfiguration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_xai_api_v1_types_proto_init() }
func file_xai_api_v1_types_proto_init() {
	if File_xai_api_v1_types_proto != nil {
		return
	}
	file_xai_api_v1_types_proto_msgTypes[4].OneofWrappers = []any{
		(*ChunkConfiguration_CharsConfiguration)(nil),
		(*ChunkConfiguration_TokensConfiguration)(nil),
		(*ChunkConfiguration_BytesConfiguration)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xai_api_v1_types_proto_rawDesc), len(file_xai_api_v1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xai_api_v1_types_proto_goTypes,
		DependencyIndexes: file_xai_api_v1_types_proto_depIdxs,
		EnumInfos:         file_xai_api_v1_types_proto_enumTypes,
		MessageInfos:      file_xai_api_v1_types_proto_msgTypes,
	}.Build()
	File_xai_api_v1_types_proto = out.File
	file_xai_api_v1_types_proto_goTypes = nil
	file_xai_api_v1_types_proto_depIdxs = nil
}
